### PR TITLE
adding archi code to sources in meta archi

### PR DESCRIPTION
**Pull request by ludomori99**
added archi code as source to be used by meta archi

### CODE REVIEW

**Review by julius-heitkoetter — COMMENTED** [review]
You may also want to change the prompts to reflect two things:

1. A2rchi is talking about itself
2. The context is code from the a2rchi repo

**Review by mdr223 — APPROVED** [review]
LGTM

**Comment by julius-heitkoetter** [comment]
We should wait until #119 is resolved to do this, since right now I believe meta A2rchi doesn't even have a data_manager associated with it, meaning that it can't even really parse documents.

**Comment by mdr223** [comment]
FYI I can work to get #119 merged after my DB class ends at 4pm

**Pull request merged**
